### ISSUE TITLE
Missing dependency pyfits

### ISSUE THREAD

**Issue by MaxNoe** [lofar-astron/PyBDSF#65] opened 2018-06-20 09:30 UTC
PyFits is required but not in setup.py

**Comment by tammojan** [comment] 2018-06-20 09:38
Hi Max! In fact, PyBDSF uses astropy.io.fits rather than pyfits (see the [astropy.io.fits FAQ](http://docs.astropy.org/en/stable/io/fits/appendix/faq.html#id5)). All imports are in a try/except to find either pyfits or astropy.io.fits. I agree that some requirements should be in setup.py, but I don't know how to find this optional dependency in setup.py.

**Comment by tammojan** [comment] 2018-06-20 09:39
Actually this is a duplicate of #62

**Closed by tammojan** 2018-06-20 09:39 UTC

**Comment by MaxNoe** [comment] 2018-06-20 10:39
Why not just stick with one? Just require astropy

**Comment by tammojan** [comment] 2018-06-20 14:11
Agree. This is a historical remnant from when pyfits was still more popular than astropy. But we can depend on a bit more modern systems now.
