### ISSUE TITLE
PyBDSF installs on Centos7 but then fails to run undefined symbol error

### ISSUE THREAD

**Issue by rhysaph** [lofar-astron/PyBDSF#105] opened 2019-07-10 14:39 UTC
Hi,
PyBDSF install fine and then fails to run, see below:

Thanks,
Rhys

 which pip
/home/rahm/anaconda3/bin/pip
rahm[trappist]rahm: pip install https://github.com/lofar-astron/PyBDSF/archive/v1.9.0.tar.gz
Collecting https://github.com/lofar-astron/PyBDSF/archive/v1.9.0.tar.gz
  Downloading https://github.com/lofar-astron/PyBDSF/archive/v1.9.0.tar.gz
     - 10.2MB 11.3MB/s
Requirement already satisfied: backports.shutil_get_terminal_size in ./anaconda3/lib/python3.7/site-packages (from bdsf==1.9.0) (1.0.0)
Requirement already satisfied: numpy in ./anaconda3/lib/python3.7/site-packages (from bdsf==1.9.0) (1.16.2)
Requirement already satisfied: scipy in ./anaconda3/lib/python3.7/site-packages (from bdsf==1.9.0) (1.2.1)
Building wheels for collected packages: bdsf
  Building wheel for bdsf (setup.py) ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-qg1ltcpv/wheels/22/89/87/6079dfa630817b49aaf1ce091fae99ab10fa3ee61b0c342bcc
Successfully built bdsf
Installing collected packages: bdsf
Successfully installed bdsf-1.9.0
32.694u 6.009s 0:15.72 246.1%	0+0k 357544+153912io 42pf+0w
rahm[trappist]rahm: pybd
pybdsf pybdsm 
rahm[trappist]rahm: pybdsf
Traceback (most recent call last):
  File "/home/rahm/anaconda3/bin/pybdsf", line 10, in <module>
    import bdsf
  File "/home/rahm/anaconda3/lib/python3.7/site-packages/bdsf/__init__.py", line 21, in <module>
    from .collapse import Op_collapse
  File "/home/rahm/anaconda3/lib/python3.7/site-packages/bdsf/collapse.py", line 11, in <module>
    from . import _cbdsm
ImportError: /home/rahm/anaconda3/lib/python3.7/site-packages/bdsf/_cbdsm.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN5boost6python6detail11init_moduleER11PyModuleDefPFvvE

**Comment by 1054** [comment] 2019-07-12 10:51
The problem is likely due to: (a) current `setup.py` needs to be updated in the way of searching `libboost_python` and `libboost_numpy` in `conda` environments, (b) `conda` libraries conflict system libraries, e.g., `libgfortran`. I did some tests in new `conda` Python3 environments in Linux and found a plausible solution as below. 

1. setup `conda` and do some checks, make sure each step has no error or empty value. 
```
conda install python=3.6 gxx_linux-64=7.2.0 gfortran_linux-64=7.2.0 boost=1.67.0 libboost=1.67.0 numpy scipy astropy matplotlib backports.shutil_get_terminal_size
echo CONDA_PREFIX=$CONDA_PREFIX
echo HOST=$HOST
echo GXX=$GXX
echo GFORTRAN=$GFORTRAN
strings $CONDA_PREFIX/lib/libstdc++.so.6.0.25 | grep "^GLIBCXX_3.4.21" # need GLIBCXX_3.4.21 for libboost=1.67.0 # and need python 3.6 because current conda libboost=1.67.0 relies on that
ls $CONDA_PREFIX/lib/libboost_python*
ls $CONDA_PREFIX/lib/libboost_numpy*
ls $CONDA_PREFIX/lib/libgfortran*
```

2. make small fixes
```
cp -i $GXX $CONDA_PREFIX/$HOST/bin/g++ # see reason below
cp -i $GFORTRAN $CONDA_PREFIX/$HOST/bin/gfortran # current PyBDSF (v1.9.0) setup.py calls gfortran, but some system gfortran is not new enough, so we use conda gfortran_linux-64=7.2.0
ln -s libboost_numpy.so $CONDA_PREFIX/lib/libboost_numpy3-py36.so # current PyBDSF (v1.9.0) setup.py looks for this file name in Linux with Python3
```

3. prepare a clean PATH for compiling
```
export PATH=$CONDA_PREFIX/$HOST/bin:$CONDA_PREFIX/bin:$(dirname $(dirname $CONDA_EXE))/condabin:/usr/local/bin:/usr/bin:/bin.
export LD_LIBRARY_PATH=
export PYTHONPATH=
```

4. compile PyBDSF
```
LDFLAGS="$LDFLAGS -shared -fPIC" \
pip \
install \
--global-option="build_ext" \
--global-option="-I$CONDA_PREFIX/include" \
--global-option="-L$CONDA_PREFIX/lib" \
--global-option="-lpython3.6m" \
--global-option="-R$CONDA_PREFIX/lib" \
https://github.com/lofar-astron/PyBDSF/archive/v1.9.0.tar.gz
```

(As also mentioned in #81, `gfortran` needs `-shared` arg in `setup.py`. And `-I$CONDA_PREFIX/include` sets the path for the compiler to find header files, i.e., solves the issue in #103. `-L$CONDA_PREFIX/lib` sets the path for finding libraries, and `-R$CONDA_PREFIX/lib` encodes the path into the produced library file so that there should have no more `undefined symbol` issue. )


5. done. 
```
python -c "import bdsf"
```

It should work now. `import bdsf` should have no error output. 

(_To PyBDSF developer:_) It seems some adjustments can be made to `setup.py`, to find more possible name patterns for `libboost_python` and `libboost_numpy` (use `conda` in priority for example if $CONDA_PREFIX exists), and try using `$GFORTRAN` in priority than `gfortran`, and add `-shared` arg, and finally set proper `include_dirs` and `library_dirs` in `Extension(name="bdsf._cbdsm", ...)`. 
It is also good to remind the user to use most suitable conda libboost+python+gxx+gfortran versions. 
It's really great to have a such powerful tool PyBDSF for scientific works!

**Comment by tammojan** [comment] 2020-04-09 07:43
I think the error that lead to the undefined symbol is that when a custom boost library is found, the include directory of a system-wide libboost is still used.

**Comment by gmloose** [comment] 2022-11-08 20:32
I'm closing this issue, since it's three years old. Feel free to open a new issue if you still encounter problems.

**Closed** 2022-11-08 20:32 UTC
