### ISSUE TITLE
Numpy 1.23x compilation crash

### ISSUE THREAD

**Issue by AlexKurek** [lofar-astron/PyBDSF#202] opened 2023-04-30 06:32 UTC
Im getting:
```
+ pip install git+https://github.com/lofar-astron/PyBDSF.git
Collecting git+https://github.com/lofar-astron/PyBDSF.git
  Cloning https://github.com/lofar-astron/PyBDSF.git to /tmp/pip-req-build-f7h8a09l
  Running command git clone -q https://github.com/lofar-astron/PyBDSF.git /tmp/pip-req-build-f7h8a09l
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmp3565qluw_in_process.py get_requires_for_build_wheel /tmp/tmpgzzmr99a
       cwd: /tmp/pip-req-build-f7h8a09l
  Complete output (124 lines):
  <string>:7: DeprecationWarning:
  
    `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
    of the deprecation of `distutils` itself. It will be removed for
    Python >= 3.12. For older Python versions it will remain present.
    It is recommended to use `setuptools < 60.0` for those Python versions.
    For more details, see:
      https://numpy.org/devdocs/reference/distutils_status_migration.html
  
  
  running egg_info
  running build_src
  INFO: build_src
  INFO: building extension "bdsf._pytesselate" sources
  INFO: f2py options: ['']
  INFO: f2py:> build/src.linux-x86_64-3.9/bdsf/_pytesselatemodule.c
  creating build
  creating build/src.linux-x86_64-3.9
  creating build/src.linux-x86_64-3.9/bdsf
  Tip: If your original code is Fortran source then you must use -m option.
  Reading fortran codes...
  	Reading file 'src/fortran/pytess_simple.f' (format:fix,strict)
  	Reading file 'src/fortran/pytess_roundness.f' (format:fix,strict)
  	Reading file 'src/fortran/constants.inc' (format:fix)
  Line #6 in src/fortran/constants.inc:"        parameter (fwsig=2.35482d0) "
  	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
  Line #7 in src/fortran/constants.inc:"        parameter (rad=57.29577951308232) "
  	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
  Line #7 in src/fortran/constants.inc:"        parameter (rad=57.29577951308232) "
  	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
  Line #8 in src/fortran/constants.inc:"        parameter (c=2.99792458d8) "
  	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
  Line #8 in src/fortran/constants.inc:"        parameter (c=2.99792458d8) "
  	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
  Line #8 in src/fortran/constants.inc:"        parameter (c=2.99792458d8) "
  	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
  Line #9 in src/fortran/constants.inc:"        parameter (bolt=1.3806505d-23) "
  	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
  Line #9 in src/fortran/constants.inc:"        parameter (bolt=1.3806505d-23) "
  	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
  Line #9 in src/fortran/constants.inc:"        parameter (bolt=1.3806505d-23) "
  	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
  Line #9 in src/fortran/constants.inc:"        parameter (bolt=1.3806505d-23) "
  	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
  Line #11 in src/fortran/constants.inc:"        parameter (sq2=1.41421356237310d0) "
  	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
  Line #11 in src/fortran/constants.inc:"        parameter (sq2=1.41421356237310d0) "
  	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
  Line #11 in src/fortran/constants.inc:"        parameter (sq2=1.41421356237310d0) "
  	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
  Line #11 in src/fortran/constants.inc:"        parameter (sq2=1.41421356237310d0) "
  	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
  Line #11 in src/fortran/constants.inc:"        parameter (sq2=1.41421356237310d0) "
  	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
  Post-processing...
  	Block: _pytesselate
  			Block: pytess_simple
  		Block: pytess_roundness
  		Block: tess_bin_complicated
  	Block: calc_area_tess
  	Block: tile_roundness
  In: src/fortran/pytess_roundness.f:tile_roundness
  get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
  In: src/fortran/pytess_roundness.f:tile_roundness
  get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
  In: src/fortran/pytess_roundness.f:tile_roundness
  get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
  In: src/fortran/pytess_roundness.f:tile_roundness
  get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
  In: src/fortran/pytess_roundness.f:tile_roundness
  get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
  In: src/fortran/pytess_roundness.f:tile_roundness
  get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
  Post-processing (stage 2)...
  Traceback (most recent call last):
    File "/tmp/tmp3565qluw_in_process.py", line 280, in <module>
      main()
    File "/tmp/tmp3565qluw_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/tmp3565qluw_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-5kkspkqy/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-5kkspkqy/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-5kkspkqy/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 483, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-5kkspkqy/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
      exec(code, locals())
    File "<string>", line 295, in <module>
    File "<string>", line 248, in main
    File "/usr/local/lib/python3.9/dist-packages/numpy/distutils/core.py", line 169, in setup
      return old_setup(**new_attr)
    File "/tmp/pip-build-env-5kkspkqy/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
      return distutils.core.setup(**attrs)
    File "/tmp/pip-build-env-5kkspkqy/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
      return run_commands(dist)
    File "/tmp/pip-build-env-5kkspkqy/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
      dist.run_commands()
    File "/tmp/pip-build-env-5kkspkqy/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
      self.run_command(cmd)
    File "/tmp/pip-build-env-5kkspkqy/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-5kkspkqy/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.9/dist-packages/numpy/distutils/command/egg_info.py", line 24, in run
      self.run_command("build_src")
    File "/tmp/pip-build-env-5kkspkqy/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
      self.distribution.run_command(command)
    File "/tmp/pip-build-env-5kkspkqy/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-5kkspkqy/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.9/dist-packages/numpy/distutils/command/build_src.py", line 144, in run
      self.build_sources()
    File "/usr/local/lib/python3.9/dist-packages/numpy/distutils/command/build_src.py", line 161, in build_sources
      self.build_extension_sources(ext)
    File "/usr/local/lib/python3.9/dist-packages/numpy/distutils/command/build_src.py", line 321, in build_extension_sources
      sources = self.f2py_sources(sources, ext)
    File "/usr/local/lib/python3.9/dist-packages/numpy/distutils/command/build_src.py", line 562, in f2py_sources
      numpy.f2py.run_main(f2py_options + ['--lower',
    File "/usr/local/lib/python3.9/dist-packages/numpy/f2py/f2py2e.py", line 469, in run_main
      raise TypeError('All blocks must be python module blocks but got %s' % (
  TypeError: All blocks must be python module blocks but got 'subroutine'
  ----------------------------------------
WARNING: Discarding git+https://github.com/lofar-astron/PyBDSF.git. Command errored out with exit status 1: /usr/bin/python3 /tmp/tmp3565qluw_in_process.py get_requires_for_build_wheel /tmp/tmpgzzmr99a Check the logs for full command output.
ERROR: Command errored out with exit status 1: /usr/bin/python3 /tmp/tmp3565qluw_in_process.py get_requires_for_build_wheel /tmp/tmpgzzmr99a Check the logs for full command output.
FATAL:   While performing build: while running engine: exit status 1
```

**Comment by gmloose** [comment] 2023-05-01 07:35
Are you using Python 3.11? If so, this is a known problem. See https://github.com/lofar-astron/PyBDSF/issues/189. Unfortunately, I haven't been able to find a solution yet.

**Comment by AlexKurek** [comment] 2023-05-01 08:01
No, Python 3.9. The soultion would be to migrate `setup.py` from distutils to setuptools<60 (if I understad well).

**Comment by gmloose** [comment] 2023-05-01 09:09
Python 3.9 should be fine. But I guess that `numpy` is the culprit here. There are some issues with `numpy >= 1.24`  that are also the source of the problems with Python 3.11.

For Python 3.9, I recommend you simply do `pip install bdsf`. There are binary wheels available for Python 3.6 .. 3.10, so there's no need to build the stuff yourself. If you insist on building it yourself, I recommend to downgrade `numpy` to `1.23`.

**Comment by AlexKurek** [comment] 2023-05-01 09:20
numpy 1.23.0 also crashes:
```
+ pip install git+https://github.com/lofar-astron/PyBDSF.git
Collecting git+https://github.com/lofar-astron/PyBDSF.git
  Cloning https://github.com/lofar-astron/PyBDSF.git to /tmp/pip-req-build-4ml_5ssp
  Running command git clone -q https://github.com/lofar-astron/PyBDSF.git /tmp/pip-req-build-4ml_5ssp
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmpv0u25y1e_in_process.py get_requires_for_build_wheel /tmp/tmpbj4w0u86
       cwd: /tmp/pip-req-build-4ml_5ssp
  Complete output (124 lines):
  <string>:7: DeprecationWarning:
  
    `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
    of the deprecation of `distutils` itself. It will be removed for
    Python >= 3.12. For older Python versions it will remain present.
    It is recommended to use `setuptools < 60.0` for those Python versions.
    For more details, see:
      https://numpy.org/devdocs/reference/distutils_status_migration.html
  
  
  running egg_info
  running build_src
  INFO: build_src
  INFO: building extension "bdsf._pytesselate" sources
  INFO: f2py options: ['']
  INFO: f2py:> build/src.linux-x86_64-3.9/bdsf/_pytesselatemodule.c
  creating build
  creating build/src.linux-x86_64-3.9
  creating build/src.linux-x86_64-3.9/bdsf
  Tip: If your original code is Fortran source then you must use -m option.
  Reading fortran codes...
  	Reading file 'src/fortran/pytess_simple.f' (format:fix,strict)
  	Reading file 'src/fortran/pytess_roundness.f' (format:fix,strict)
  	Reading file 'src/fortran/constants.inc' (format:fix)
  Line #6 in src/fortran/constants.inc:"        parameter (fwsig=2.35482d0) "
  	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
  Line #7 in src/fortran/constants.inc:"        parameter (rad=57.29577951308232) "
  	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
  Line #7 in src/fortran/constants.inc:"        parameter (rad=57.29577951308232) "
  	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
  Line #8 in src/fortran/constants.inc:"        parameter (c=2.99792458d8) "
  	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
  Line #8 in src/fortran/constants.inc:"        parameter (c=2.99792458d8) "
  	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
  Line #8 in src/fortran/constants.inc:"        parameter (c=2.99792458d8) "
  	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
  Line #9 in src/fortran/constants.inc:"        parameter (bolt=1.3806505d-23) "
  	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
  Line #9 in src/fortran/constants.inc:"        parameter (bolt=1.3806505d-23) "
  	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
  Line #9 in src/fortran/constants.inc:"        parameter (bolt=1.3806505d-23) "
  	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
  Line #9 in src/fortran/constants.inc:"        parameter (bolt=1.3806505d-23) "
  	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
  Line #11 in src/fortran/constants.inc:"        parameter (sq2=1.41421356237310d0) "
  	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
  Line #11 in src/fortran/constants.inc:"        parameter (sq2=1.41421356237310d0) "
  	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
  Line #11 in src/fortran/constants.inc:"        parameter (sq2=1.41421356237310d0) "
  	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
  Line #11 in src/fortran/constants.inc:"        parameter (sq2=1.41421356237310d0) "
  	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
  Line #11 in src/fortran/constants.inc:"        parameter (sq2=1.41421356237310d0) "
  	get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
  Post-processing...
  	Block: _pytesselate
  			Block: pytess_simple
  		Block: pytess_roundness
  		Block: tess_bin_complicated
  	Block: calc_area_tess
  	Block: tile_roundness
  In: src/fortran/pytess_roundness.f:tile_roundness
  get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
  In: src/fortran/pytess_roundness.f:tile_roundness
  get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
  In: src/fortran/pytess_roundness.f:tile_roundness
  get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
  In: src/fortran/pytess_roundness.f:tile_roundness
  get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
  In: src/fortran/pytess_roundness.f:tile_roundness
  get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
  In: src/fortran/pytess_roundness.f:tile_roundness
  get_parameters: got "eval() arg 1 must be a string, bytes or code object" on 4
  Post-processing (stage 2)...
  Traceback (most recent call last):
    File "/tmp/tmpv0u25y1e_in_process.py", line 280, in <module>
      main()
    File "/tmp/tmpv0u25y1e_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/tmpv0u25y1e_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-to18exxr/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-to18exxr/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-to18exxr/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 483, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-to18exxr/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
      exec(code, locals())
    File "<string>", line 295, in <module>
    File "<string>", line 248, in main
    File "/usr/local/lib/python3.9/dist-packages/numpy/distutils/core.py", line 169, in setup
      return old_setup(**new_attr)
    File "/tmp/pip-build-env-to18exxr/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
      return distutils.core.setup(**attrs)
    File "/tmp/pip-build-env-to18exxr/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
      return run_commands(dist)
    File "/tmp/pip-build-env-to18exxr/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
      dist.run_commands()
    File "/tmp/pip-build-env-to18exxr/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
      self.run_command(cmd)
    File "/tmp/pip-build-env-to18exxr/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-to18exxr/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.9/dist-packages/numpy/distutils/command/egg_info.py", line 24, in run
      self.run_command("build_src")
    File "/tmp/pip-build-env-to18exxr/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
      self.distribution.run_command(command)
    File "/tmp/pip-build-env-to18exxr/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-to18exxr/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.9/dist-packages/numpy/distutils/command/build_src.py", line 144, in run
      self.build_sources()
    File "/usr/local/lib/python3.9/dist-packages/numpy/distutils/command/build_src.py", line 161, in build_sources
      self.build_extension_sources(ext)
    File "/usr/local/lib/python3.9/dist-packages/numpy/distutils/command/build_src.py", line 321, in build_extension_sources
      sources = self.f2py_sources(sources, ext)
    File "/usr/local/lib/python3.9/dist-packages/numpy/distutils/command/build_src.py", line 562, in f2py_sources
      numpy.f2py.run_main(f2py_options + ['--lower',
    File "/usr/local/lib/python3.9/dist-packages/numpy/f2py/f2py2e.py", line 469, in run_main
      raise TypeError('All blocks must be python module blocks but got %s' % (
  TypeError: All blocks must be python module blocks but got 'subroutine'
  ----------------------------------------
WARNING: Discarding git+https://github.com/lofar-astron/PyBDSF.git. Command errored out with exit status 1: /usr/bin/python3 /tmp/tmpv0u25y1e_in_process.py get_requires_for_build_wheel /tmp/tmpbj4w0u86 Check the logs for full command output.
ERROR: Command errored out with exit status 1: /usr/bin/python3 /tmp/tmpv0u25y1e_in_process.py get_requires_for_build_wheel /tmp/tmpbj4w0u86 Check the logs for full command output.
FATAL:   While performing build: while running engine: exit status 1
```
Im just reporting, for me its OK, I can keep using numpy 1.22.4.

**Comment by gmloose** [comment] 2023-05-01 09:35
I cannot reproduce the issue if I start with a plain `python:3.9` docker image. So it's probably something in your local setup that's wreaking havoc. Have you tried using a `virtualenv`?

**Comment by AlexKurek** [comment] 2023-05-01 09:52
Im doing this using Singularity recipe. I attach it in case you wolud want to chceck whats going on. It is based on:
https://github.com/mhardcastle/ddf-pipeline/blob/master/ddf-py3.singularity

[ddf-py3.singularity_opt.zip](https://github.com/lofar-astron/PyBDSF/files/11364798/ddf-py3.singularity_opt.zip)

If there is `numpy==1.22.4` in line 68, this works fine.

**Comment by gmloose** [comment] 2023-05-01 10:23
Then I recommend that you use `numpy==1.22.4`. Like I said, this is not a PyBDSF problem, because it works fine in a plain Python 3.9 environment. It has to do with your local setup, which is your case happens to be a Singularity image you're building yourself.

BTW: I see that the script on GitHub uses `pip install bdsf`, whereas the Bash script in the zip-file you linked to uses `pip install git+https://github.com/lofar-astron/PyBDSF.git`. I recommend to use the former command.

I'm closing this issue, but feel free to re-open if you think this is incorrect.

**Closed by gmloose** 2023-05-01 10:23 UTC

**Comment by fschramka** [comment] 2023-07-10 21:30
This is actually a numpy problem - the issue is written right there in the log. 

      `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
    of the deprecation of `distutils` itself. It will be removed for
    Python >= 3.12. For older Python versions it will remain present.
    It is recommended to use `setuptools < 60.0` for those Python versions.
    For more details, see:
      https://numpy.org/devdocs/reference/distutils_status_migration.html

Hence even if you use Python 3.7+ with a newer numpy version (>1.23) the installation will fail). 

@AlexKurek 
There is a workaround right now for never numpy versions. 
1. Make a new venv / conda env. 
2. Install python 3.9
3. Install numpy 1.25
4. Clone the repo
5. Change in pyproject.toml "setuptools<65.6", into "setuptools>=68"
6. Install everything with: `pip install .`

Worked for me and it create  bdsf 1.11.0a1 (not stable version - whatever, the `tbdsf_process_image.py` test ran through :) (casacore needs to be installed)

Carefull, when you repeat the process by running `pip install .` again. It will fail with the following error message:

`CMake Error at /tmp/pip-build-env-o618ripl/overlay/lib/python3.9/site-packages/skbuild/resources/cmake/FindF2PY.cmake:92 (add_library):
        No SOURCES given to target: _f2py_runtime_library`

The reason is, that the `_skbuild` folder is still there. Delete it before installing it again with pip, to make this issue go away :) @gmloose Maybe this folder should get cleared after the installation anyway? But this is another issue :)

**Comment by gmloose** [comment] 2023-07-12 09:18
@AlexKurek, I've been bitten by the issue of a lingering `_skbuild` directory myself multiple times. There's no easy way to fix this. I think this should be fixed in `scikit-build` itself.
