### ISSUE TITLE
'Image' object has no attribute 'resid_gaus_arr' when trying to perform fits on a .fit file

### ISSUE THREAD

**Issue by jt2553** [lofar-astron/PyBDSF#152] opened 2021-03-20 22:22 UTC
I have a set of images that have been processed by casa, including tclean using mtmfs and widebandpbcor.  The images have been exported as fits files.
Each fits file has had sources detected using SEP, then confirmed by using imfits and imstat in casa.
I reasonably confident, therefore, that the images should work in PyBDSF, and I'd like to use it to double (triple?) check the gaussian fits I have already - mostly point sources.
For each image I have tried so far I get the following error when pybdsf is trying to perform the routine "Displaying islands and rms image.":

AttributeError: 'Image' object has no attribute 'resid_gaus_arr'

I read in another issue post from Jan 2020 that this was fixed for someone following an example file.  I have the latest version of pybdsf (as far as I know, having downloaded it this morning), Can someone help me?

**Comment by jt2553** [comment] 2021-03-20 22:50
Update - seems to only be a problem in interactive=True

**Comment by vmahat** [comment] 2023-01-24 11:19
I see this has not been active for a while, but I cannot find any solution for this as I am having the same problem. It is possible that an island may be overlapping or reaching the edge of an image -- when I use an extremely high 'thresh_pix' or 'thresh_isl', and detect emission from just the centre of the image, I do not get the error and a fit converges.

**Comment by gmloose** [comment] 2023-01-24 14:33
Could you provide a bit more background information, please.

- Which post from Jan 2020 are you referring to?
- Do you have a backtrace when the `AttributeError` is raised?

**Comment by vmahat** [comment] 2023-01-24 14:38
Referring to the post from March 2021 https://github.com/lofar-astron/PyBDSF/issues/152#issue-836923259:

> I have a set of images that have been processed by casa, including tclean using mtmfs and widebandpbcor. The images have been exported as fits files. Each fits file has had sources detected using SEP, then confirmed by using imfits and imstat in casa. I reasonably confident, therefore, that the images should work in PyBDSF, and I'd like to use it to double (triple?) check the gaussian fits I have already - mostly point sources. For each image I have tried so far I get the following error when pybdsf is trying to perform the routine "Displaying islands and rms image.":
> 
> AttributeError: 'Image' object has no attribute 'resid_gaus_arr'
> 
> I read in another issue post from Jan 2020 that this was fixed for someone following an example file. I have the latest version of pybdsf (as far as I know, having downloaded it this morning), Can someone help me?

I have copied the backtrace below:

```
Derived rms_box (box size, step size) ... : (291, 97) pixels
--> Size of rms_box larger than 1/4 of image size
--> Using constant background rms and mean
Value of background rms ................. : 3.00e-05 Jy/beam
Value of background mean ................ : 5e-05 Jy/beam
--> Expected 5-sigma-clipped false detection rate < fdr_ratio
--> Using sigma-clipping ('hard') thresholding
Minimum number of pixels per island ..... : 6
Number of islands found ................. : 66
--> Displaying islands and rms image...
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/opt/lofar/pyenv-py2/lib64/python2.7/site-packages/bdsf-1.10.1-py2.7-linux-x86_64.egg/bdsf/pybdsf.pyc in <module>()
----> 1 process_image(filename='3C353C-X_.44I.fits', thresh_isl=3.0, beam=(1.2222e-4,1.2222e-4,0), interactive=True, atrous_do=True, rms_map=False, rms_value=30e-6)

/opt/lofar/pyenv-py2/lib64/python2.7/site-packages/bdsf-1.10.1-py2.7-linux-x86_64.egg/bdsf/pybdsf.pyc in process_image(**kwargs)
    362     # from the Image object, so we don't need to get_task_kwargs as
    363     # we do for the other tasks.
--> 364     success = _img.process(**kwargs)
    365 
    366     # Now restore parameters and save to pybdsf.last

/opt/lofar/pyenv-py2/lib64/python2.7/site-packages/bdsf-1.10.1-py2.7-linux-x86_64.egg/bdsf/image.pyc in process(self, **kwargs)
    133         """Process Image object"""
    134         from . import interface
--> 135         success = interface.process(self, **kwargs)
    136         return success
    137 

/opt/lofar/pyenv-py2/lib64/python2.7/site-packages/bdsf-1.10.1-py2.7-linux-x86_64.egg/bdsf/interface.pyc in process(img, **kwargs)
     60         img, op_chain = get_op_chain(img)
     61         if op_chain is not None:
---> 62             _run_op_list(img, op_chain)
     63             img._prev_opts = img.opts.to_dict()
     64         return True

/opt/lofar/pyenv-py2/lib64/python2.7/site-packages/bdsf-1.10.1-py2.7-linux-x86_64.egg/bdsf/__init__.pyc in _run_op_list(img, chain)
    142                 img.show_fit(rms_image=True, mean_image=True,
    143                     ch0_islands=True, gresid_image=False, sresid_image=False,
--> 144                     gmodel_image=False, smodel_image=False, pyramid_srcs=False)
    145             prompt = dc + "Press enter to continue or 'q' to quit .. : " + nc
    146             answ = raw_input_no_history(prompt)

/opt/lofar/pyenv-py2/lib64/python2.7/site-packages/bdsf-1.10.1-py2.7-linux-x86_64.egg/bdsf/image.pyc in show_fit(self, **kwargs)
    172             print('Image has not been processed. Please run process_image first.')
    173             return False
--> 174         plotresults.plotresults(self, **kwargs)
    175         return True
    176 

/opt/lofar/pyenv-py2/lib64/python2.7/site-packages/bdsf-1.10.1-py2.7-linux-x86_64.egg/bdsf/plotresults.pyc in plotresults(img, ch0_image, rms_image, mean_image, ch0_islands, gresid_image, sresid_image, gmodel_image, smodel_image, pyramid_srcs, source_seds, ch0_flagged, pi_image, psf_major, psf_minor, psf_pa, broadcast)
    206     im_mean = img.clipped_mean
    207     im_rms = img.clipped_rms
--> 208     if img.resid_gaus_arr is None:
    209         low = 1.1*abs(img.min_value)
    210     else:

/opt/lofar/pyenv-py2/lib64/python2.7/site-packages/bdsf-1.10.1-py2.7-linux-x86_64.egg/bdsf/image.pyc in __getattribute__(self, name)
     82                     return object.__getattribute__(self, name)
     83             else:
---> 84                 return object.__getattribute__(self, name)
     85         else:
     86             return object.__getattribute__(self, name)

AttributeError: 'Image' object has no attribute 'resid_gaus_arr'
```

**Comment by gmloose** [comment] 2023-01-24 14:45
Thanks. Do you maybe have a simple test case, and a description of the steps you took that resulted in this error? This will help us to reproduce the issue. We may need a small FITS image as well to work with, I guess.

**Comment by vmahat** [comment] 2023-01-24 15:39
This usually happens on a case by case basis, and not on images of simple objects. You can use the original fits image used here (downloadable from the dropbox link below, which I will delete later..)

https://www.dropbox.com/s/gyjoz6u0uqg7pvk/3C353C-X_.44I.fits?dl=0

The pybdsf command is `process_image(filename='3C353C-X_.44I.fits', thresh_isl=5.0, interactive=False)`

**Comment by gmloose** [comment] 2023-01-24 16:24
I'm curious. Did you build `bdsf` yourself from source? I'm asking because support for Python 2.7 was dropped with the release of version 1.10, but I see you're using 1.10.1 and Python 2.7.

Also, thus far, I've not been able to reproduce the issue, using the binary wheel for `bdsf` 1.10.1 and Python 3.8.

**Comment by gmloose** [comment] 2023-01-24 16:42
I've built `bdsf` 1.10.1 in a Docker container based on the `python:2.7` Docker image. Again, I'm unable to reproduce the issue you're having. Sorry.

**Comment by vmahat** [comment] 2023-01-24 16:54
I seem to have homed into the issue. You were right, my system was running on python 2.7.12, and this information seemed to 'leak' into the singularity container through which I was running pybdsf. When I ran pybdsf (the same version) on a machine using python3 (using the --cleanenv option in the singularity command to clean environments), it worked.

**Comment by gmloose** [comment] 2023-01-25 08:29
I'm glad you sorted it out. I will close this issue then.

**Closed by gmloose** 2023-01-25 08:29 UTC
