### ISSUE TITLE
'Image' object has no attribute 'pixel_beamarea' when running process_image ... gausfit

### ISSUE THREAD

**Issue by gabicca** [lofar-astron/PyBDSF#161] opened 2021-08-09 12:50 UTC
The following exception occurs when I call `bdsf.process_image`, and when it gets to the `gausfit` method at https://github.com/lofar-astron/PyBDSF/blob/master/bdsf/gausfit.py#L103

I've installed the latest code from master, and it's running on Python 3.8.5.

```
Thread raised exception 'Image' object has no attribute 'pixel_beamarea'
Traceback of thread is:
-------------------------
-------------------------
  File "...lib/python3.8/site-packages/bdsf/multi_proc.py", line 54, in worker
    result = f(val)
  File "...lib/python3.8/site-packages/bdsf/functions.py", line 2061, in eval_func_tuple
    return f_args[0](*f_args[1:])
  File "...lib/python3.8/site-packages/bdsf/gausfit.py", line 223, in process_island
    size = isl.size_active/img.pixel_beamarea()*2.0   # 2.0 roughly corrects for thresh_isl
  File "...lib/python3.8/site-packages/bdsf/image.py", line 86, in __getattribute__
    return object.__getattribute__(self, name)
...lib/python3.8/runpy.py:127: RuntimeWarning: 'bdsf.gausfit' found in sys.modules after import of package 'bdsf', but prior to execution of 'bdsf.gausfit'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Thread raised exception 'Image' object has no attribute 'pixel_beamarea'
Traceback of thread is:
-------------------------
-------------------------
  File "...lib/python3.8/site-packages/bdsf/multi_proc.py", line 54, in worker
    result = f(val)
  File "...lib/python3.8/site-packages/bdsf/functions.py", line 2061, in eval_func_tuple
    return f_args[0](*f_args[1:])
  File "...lib/python3.8/site-packages/bdsf/gausfit.py", line 223, in process_island
    size = isl.size_active/img.pixel_beamarea()*2.0   # 2.0 roughly corrects for thresh_isl
  File "...lib/python3.8/site-packages/bdsf/image.py", line 86, in __getattribute__
    return object.__getattribute__(self, name)
...lib/python3.8/runpy.py:127: RuntimeWarning: 'bdsf.gausfit' found in sys.modules after import of package 'bdsf', but prior to execution of 'bdsf.gausfit'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Thread raised exception 'Image' object has no attribute 'pixel_beamarea'
Traceback of thread is:
-------------------------
-------------------------
  File "...lib/python3.8/site-packages/bdsf/multi_proc.py", line 54, in worker
    result = f(val)
  File "...lib/python3.8/site-packages/bdsf/functions.py", line 2061, in eval_func_tuple
    return f_args[0](*f_args[1:])
  File "...lib/python3.8/site-packages/bdsf/gausfit.py", line 223, in process_island
    size = isl.size_active/img.pixel_beamarea()*2.0   # 2.0 roughly corrects for thresh_isl
  File "...lib/python3.8/site-packages/bdsf/image.py", line 86, in __getattribute__
    return object.__getattribute__(self, name)
Traceback (most recent call last):
  File "...lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-fcdf1091465e>", line 1, in <module>
    mp.parallel_map(func.eval_func_tuple,
  File "...lib/python3.8/site-packages/bdsf/multi_proc.py", line 223, in parallel_map
    results = run_tasks(procs, err_q, out_q, len(sequence))
  File "...lib/python3.8/site-packages/bdsf/multi_proc.py", line 114, in run_tasks
    raise err_q.get()
  File "...lib/python3.8/site-packages/bdsf/multi_proc.py", line 54, in worker
    result = f(val)
  File "...lib/python3.8/site-packages/bdsf/functions.py", line 2061, in eval_func_tuple
    return f_args[0](*f_args[1:])
  File "...lib/python3.8/site-packages/bdsf/gausfit.py", line 223, in process_island
    size = isl.size_active/img.pixel_beamarea()*2.0   # 2.0 roughly corrects for thresh_isl
  File "...lib/python3.8/site-packages/bdsf/image.py", line 86, in __getattribute__
    return object.__getattribute__(self, name)
AttributeError: 'Image' object has no attribute 'pixel_beamarea'
```

**Comment by darafferty** [comment] 2021-08-24 09:51
Thanks for reporting this. I can't reproduce the problem myself--could you please post the non-default parameters you used (if any)?

**Comment by gabicca** [comment] 2021-09-07 07:55
Hi @darafferty,

Sorry for the slow reply. We've been going through an upgrade of our package, to use python3.9, and I wanted to wait to see if I still get the same error when that's done.

And yes, it's still there. Looks like it happens on MacOS (Mojave), but doesn't seem to happen on Linux.

It occurs for various parameters, here are the ones that are changed in `bdsf.process_image`:

- beam=(0.02864788975654116, 0.01432394487827058, 0.0)
- thresh_isl=5.0
- thresh_pix=10.0
- quiet=False

The input image is a FITS file. I've got the feeling you will need that too?

**Comment by darafferty** [comment] 2021-09-23 15:38
Thanks for the detailed info -- I updated Python on my Mac and can reproduce the problem now. After much head scratching, I found that the problem is apparently due to the way that the multiprocessing module spawns processes in Python 3.8+ on macOS (e.g., see https://github.com/ipython/ipython/issues/12396). I've made a fix for this on the master branch -- can you please try updating and see if this fixes the problem?

**Comment by gabicca** [comment] 2021-09-24 10:25
Hi @darafferty,

Thanks! I can confirm that the fix worked. I no longer see the reported error.

**Comment by darafferty** [comment] 2021-09-24 10:51
Great! Thanks for confirming.

**Closed by darafferty** 2021-09-24 10:51 UTC
